packages:
  - "backend"
  - "frontend"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true

overrides:
  multer: 2.2.0
  js-yaml: 4.3.0
  "brace-expansion@1.1.15": 1.1.16
  "brace-expansion@2.1.1": 2.1.2
  "brace-expansion@5.0.6": 5.0.8
  "shell-quote@1.8.4": 1.10.0
