import { relativeDate } from './dates';

export const expenses = [
  {
    vendorName: 'Atlas Office Supplies',
    categoryName: 'Office',
    description: 'Printer paper and stationery restock',
    amount: '1250.50',
    expenseDate: relativeDate(-150),
    notes: 'Monthly office supply purchase.',
  },
  {
    vendorName: 'Nova Tech Solutions',
    categoryName: 'Software',
    description: 'Team collaboration software renewal',
    amount: '3499.00',
    expenseDate: relativeDate(-143),
    notes: 'Quarterly SaaS subscription payment.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: 'Food',
    description: 'Pantry and refreshments restock',
    amount: '680.25',
    expenseDate: relativeDate(-137),
    notes: 'Snacks, coffee, and bottled water.',
  },
  {
    vendorName: 'Bright Print Studio',
    categoryName: null,
    description: 'Business cards and event flyers',
    amount: '940.00',
    expenseDate: relativeDate(-131),
    notes: 'Printed collateral for local event.',
    archivedAt: relativeDate(-45),
  },
  {
    vendorName: 'Urban Delivery Co',
    categoryName: 'Travel',
    description: 'Same-day package deliveries',
    amount: '310.75',
    expenseDate: relativeDate(-125),
    notes: 'Client document and sample deliveries.',
  },
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud hosting invoice',
    amount: '2190.00',
    expenseDate: relativeDate(-118),
    notes: 'Monthly infrastructure and storage costs.',
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Social media campaign design',
    amount: '1750.00',
    expenseDate: relativeDate(-111),
    notes: 'Creative assets for seasonal promotion.',
  },
  {
    vendorName: 'SafeBuild Maintenance',
    categoryName: 'Maintenance',
    description: 'Air conditioning maintenance visit',
    amount: '890.00',
    expenseDate: relativeDate(-104),
    notes: 'Routine preventive maintenance.',
  },
  {
    vendorName: 'Metro Fuel Services',
    categoryName: 'Fuel',
    description: 'Vehicle fuel card top-up',
    amount: '1450.00',
    expenseDate: relativeDate(-97),
    notes: 'Operations vehicle monthly fuel budget.',
  },
  {
    vendorName: 'PureClean Supplies',
    categoryName: 'Cleaning',
    description: 'Cleaning products replenishment',
    amount: '560.40',
    expenseDate: relativeDate(-90),
    notes: 'Sanitizer, soap, and surface cleaner restock.',
  },
  {
    vendorName: 'Northstar Coworking',
    categoryName: 'Office',
    description: 'Meeting room booking',
    amount: '750.00',
    expenseDate: relativeDate(-83),
    notes: 'Half-day planning session for the product team.',
  },
  {
    vendorName: 'Harbor Business Travel',
    categoryName: 'Travel',
    description: 'Client visit accommodation',
    amount: '2860.00',
    expenseDate: relativeDate(-76),
    notes: 'Two-night stay for an on-site client workshop.',
  },
  {
    vendorName: 'SecureNet Systems',
    categoryName: 'Software',
    description: 'Endpoint security licenses',
    amount: '4200.00',
    expenseDate: relativeDate(-69),
    notes: 'Annual protection for twelve workstations.',
  },
  {
    vendorName: 'Cedar Office Furniture',
    categoryName: 'Office',
    description: 'Ergonomic office chairs',
    amount: '7350.00',
    expenseDate: relativeDate(-62),
    notes: 'Five adjustable chairs for the main workspace.',
  },
  {
    vendorName: 'Harbor Conference Center',
    categoryName: null,
    includeProof: false,
    description: 'Customer workshop venue',
    amount: '5100.00',
    expenseDate: relativeDate(-55),
    notes: 'Room hire and audiovisual equipment.',
  },
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud hosting invoice',
    amount: '2245.00',
    expenseDate: relativeDate(-48),
    notes: 'Monthly infrastructure and storage costs.',
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Product launch photography',
    amount: '3200.00',
    expenseDate: relativeDate(-41),
    notes: 'Studio session and edited product photographs.',
  },
  {
    vendorName: 'Urban Delivery Co',
    categoryName: 'Travel',
    description: 'Regional sample deliveries',
    amount: '485.50',
    expenseDate: relativeDate(-34),
    notes: 'Samples delivered to three prospective clients.',
  },
  {
    vendorName: 'Atlas Office Supplies',
    categoryName: 'Office',
    description: 'Archive storage boxes',
    amount: '420.00',
    expenseDate: relativeDate(-27),
    notes: 'Supplies for the records retention cleanup.',
    archivedAt: relativeDate(-18),
  },
  {
    vendorName: 'SafeBuild Maintenance',
    categoryName: null,
    includeProof: false,
    description: 'Emergency plumbing repair',
    amount: '1325.75',
    expenseDate: relativeDate(-20),
    notes: 'After-hours repair in the office kitchen.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: null,
    includeProof: false,
    description: 'Team planning lunch',
    amount: '845.20',
    expenseDate: relativeDate(-13),
    notes: 'Lunch during the quarterly planning workshop.',
  },
  {
    vendorName: 'Bright Print Studio',
    categoryName: null,
    includeProof: false,
    description: 'Updated service brochures',
    amount: '1180.00',
    expenseDate: relativeDate(-6),
    notes: 'Short print run for the revised service catalog.',
    archivedAt: relativeDate(-2),
  },
  {
    vendorName: 'Nova Tech Solutions',
    categoryName: null,
    includeProof: false,
    description: 'Monitor stand purchase',
    amount: '189.99',
    expenseDate: relativeDate(-3),
    notes: 'Pending category assignment and receipt upload.',
  },
];
