export const expenses = [
  {
    vendorName: 'Atlas Office Supplies',
    categoryName: 'Office',
    description: 'Printer paper and stationery restock',
    amount: '1250.50',
    expenseDate: new Date('2026-01-15T00:00:00.000Z'),
    notes: 'Monthly office supply purchase.',
  },
  {
    vendorName: 'Nova Tech Solutions',
    categoryName: 'Software',
    description: 'Team collaboration software renewal',
    amount: '3499.00',
    expenseDate: new Date('2026-01-20T00:00:00.000Z'),
    notes: 'Quarterly SaaS subscription payment.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: 'Food',
    description: 'Pantry and refreshments restock',
    amount: '680.25',
    expenseDate: new Date('2026-01-22T00:00:00.000Z'),
    notes: 'Snacks, coffee, and bottled water.',
  },
  {
    vendorName: 'Bright Print Studio',
    categoryName: 'Printing',
    description: 'Business cards and event flyers',
    amount: '940.00',
    expenseDate: new Date('2026-01-25T00:00:00.000Z'),
    notes: 'Printed collateral for local event.',
  },
  {
    vendorName: 'Urban Delivery Co',
    categoryName: 'Travel',
    description: 'Same-day package deliveries',
    amount: '310.75',
    expenseDate: new Date('2026-01-27T00:00:00.000Z'),
    notes: 'Client document and sample deliveries.',
  },
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud hosting invoice',
    amount: '2190.00',
    expenseDate: new Date('2026-02-01T00:00:00.000Z'),
    notes: 'Monthly infrastructure and storage costs.',
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Social media campaign design',
    amount: '1750.00',
    expenseDate: new Date('2026-02-04T00:00:00.000Z'),
    notes: 'Creative assets for seasonal promotion.',
  },
  {
    vendorName: 'SafeBuild Maintenance',
    categoryName: 'Maintenance',
    description: 'Air conditioning maintenance visit',
    amount: '890.00',
    expenseDate: new Date('2026-02-07T00:00:00.000Z'),
    notes: 'Routine preventive maintenance.',
  },
  {
    vendorName: 'Metro Fuel Services',
    categoryName: 'Fuel',
    description: 'Vehicle fuel card top-up',
    amount: '1450.00',
    expenseDate: new Date('2026-02-10T00:00:00.000Z'),
    notes: 'Operations vehicle monthly fuel budget.',
  },
  {
    vendorName: 'PureClean Supplies',
    categoryName: 'Cleaning',
    description: 'Cleaning products replenishment',
    amount: '560.40',
    expenseDate: new Date('2026-02-12T00:00:00.000Z'),
    notes: 'Sanitizer, soap, and surface cleaner restock.',
  },
];
