export const expenses = [
  {
    vendorName: 'Atlas Office Supplies',
    categoryName: 'Office',
    description: 'Printer paper and stationery restock',
    amount: '1250.50',
    expenseDate: new Date('2026-01-15T00:00:00.000Z'),
    notes: 'Monthly office supply purchase.',
  },
  {
    vendorName: 'Nova Tech Solutions',
    categoryName: 'Software',
    description: 'Team collaboration software renewal',
    amount: '3499.00',
    expenseDate: new Date('2026-01-20T00:00:00.000Z'),
    notes: 'Quarterly SaaS subscription payment.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: 'Food',
    description: 'Pantry and refreshments restock',
    amount: '680.25',
    expenseDate: new Date('2026-01-22T00:00:00.000Z'),
    notes: 'Snacks, coffee, and bottled water.',
  },
  {
    vendorName: 'Bright Print Studio',
    categoryName: 'Printing',
    description: 'Business cards and event flyers',
    amount: '940.00',
    expenseDate: new Date('2026-01-25T00:00:00.000Z'),
    notes: 'Printed collateral for local event.',
  },
  {
    vendorName: 'Urban Delivery Co',
    categoryName: 'Travel',
    description: 'Same-day package deliveries',
    amount: '310.75',
    expenseDate: new Date('2026-01-27T00:00:00.000Z'),
    notes: 'Client document and sample deliveries.',
  },
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud hosting invoice',
    amount: '2190.00',
    expenseDate: new Date('2026-02-01T00:00:00.000Z'),
    notes: 'Monthly infrastructure and storage costs.',
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Social media campaign design',
    amount: '1750.00',
    expenseDate: new Date('2026-02-04T00:00:00.000Z'),
    notes: 'Creative assets for seasonal promotion.',
  },
  {
    vendorName: 'SafeBuild Maintenance',
    categoryName: 'Maintenance',
    description: 'Air conditioning maintenance visit',
    amount: '890.00',
    expenseDate: new Date('2026-02-07T00:00:00.000Z'),
    notes: 'Routine preventive maintenance.',
  },
  {
    vendorName: 'Metro Fuel Services',
    categoryName: 'Fuel',
    description: 'Vehicle fuel card top-up',
    amount: '1450.00',
    expenseDate: new Date('2026-02-10T00:00:00.000Z'),
    notes: 'Operations vehicle monthly fuel budget.',
  },
  {
    vendorName: 'PureClean Supplies',
    categoryName: 'Cleaning',
    description: 'Cleaning products replenishment',
    amount: '560.40',
    expenseDate: new Date('2026-02-12T00:00:00.000Z'),
    notes: 'Sanitizer, soap, and surface cleaner restock.',
  },
  {
    vendorName: 'Northstar Coworking',
    categoryName: 'Office',
    description: 'Meeting room booking',
    amount: '750.00',
    expenseDate: new Date('2026-03-05T00:00:00.000Z'),
    notes: 'Half-day planning session for the product team.',
  },
  {
    vendorName: 'Riad Business Travel',
    categoryName: 'Travel',
    description: 'Client visit accommodation',
    amount: '2860.00',
    expenseDate: new Date('2026-03-18T00:00:00.000Z'),
    notes: 'Two-night stay for an on-site client workshop.',
  },
  {
    vendorName: 'SecureNet Systems',
    categoryName: 'Software',
    description: 'Endpoint security licenses',
    amount: '4200.00',
    expenseDate: new Date('2026-04-02T00:00:00.000Z'),
    notes: 'Annual protection for twelve workstations.',
  },
  {
    vendorName: 'Cedar Office Furniture',
    categoryName: 'Office',
    description: 'Ergonomic office chairs',
    amount: '7350.00',
    expenseDate: new Date('2026-04-21T00:00:00.000Z'),
    notes: 'Five adjustable chairs for the main workspace.',
  },
  {
    vendorName: 'Harbor Conference Center',
    categoryName: 'Marketing',
    description: 'Customer workshop venue',
    amount: '5100.00',
    expenseDate: new Date('2026-05-14T00:00:00.000Z'),
    notes: 'Room hire and audiovisual equipment.',
  },
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud hosting invoice',
    amount: '2245.00',
    expenseDate: new Date('2026-05-31T00:00:00.000Z'),
    notes: 'Monthly infrastructure and storage costs.',
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Product launch photography',
    amount: '3200.00',
    expenseDate: new Date('2026-06-11T00:00:00.000Z'),
    notes: 'Studio session and edited product photographs.',
  },
  {
    vendorName: 'Urban Delivery Co',
    categoryName: 'Travel',
    description: 'Regional sample deliveries',
    amount: '485.50',
    expenseDate: new Date('2026-06-24T00:00:00.000Z'),
    notes: 'Samples delivered to three prospective clients.',
  },
  {
    vendorName: 'Atlas Office Supplies',
    categoryName: 'Office',
    description: 'Archive storage boxes',
    amount: '420.00',
    expenseDate: new Date('2026-07-03T00:00:00.000Z'),
    notes: 'Supplies for the records retention cleanup.',
    archivedAt: new Date('2026-07-18T09:30:00.000Z'),
  },
  {
    vendorName: 'SafeBuild Maintenance',
    categoryName: 'Maintenance',
    description: 'Emergency plumbing repair',
    amount: '1325.75',
    expenseDate: new Date('2026-07-16T00:00:00.000Z'),
    notes: 'After-hours repair in the office kitchen.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: 'Food',
    description: 'Team planning lunch',
    amount: '845.20',
    expenseDate: new Date('2026-07-29T00:00:00.000Z'),
    notes: 'Lunch during the quarterly planning workshop.',
  },
  {
    vendorName: 'Bright Print Studio',
    categoryName: 'Printing',
    description: 'Updated service brochures',
    amount: '1180.00',
    expenseDate: new Date('2026-08-04T00:00:00.000Z'),
    notes: 'Short print run for the revised service catalog.',
  },
];
