import { relativeDate } from './dates';

export const recurringExpenseTemplates = [
  {
    vendorName: 'CloudPoint Hosting',
    categoryName: 'Utilities',
    description: 'Cloud infrastructure subscription',
    amount: '2245.00',
    currency: 'USD',
    frequency: 'MONTHLY' as const,
    nextDueDate: relativeDate(-2),
    notes: 'Monthly hosting, storage, and infrastructure services.',
  },
  {
    vendorName: 'Green Market Foods',
    categoryName: 'Food',
    description: 'Office pantry delivery',
    amount: '680.25',
    currency: 'USD',
    frequency: 'MONTHLY' as const,
    nextDueDate: relativeDate(5),
    notes: 'Monthly snacks, coffee, and refreshments delivery.',
  },
  {
    vendorName: 'SecureNet Systems',
    categoryName: 'Software',
    description: 'Endpoint protection renewal',
    amount: '4200.00',
    currency: 'USD',
    frequency: 'YEARLY' as const,
    nextDueDate: relativeDate(2),
    notes: 'Annual endpoint-protection renewal for twelve workstations.',
  },
  {
    vendorName: 'Legacy Telecom Services',
    categoryName: 'Legacy communications',
    description: 'Office telephone service',
    amount: '980.00',
    currency: 'USD',
    frequency: 'MONTHLY' as const,
    nextDueDate: relativeDate(-45),
    notes: 'Retired telephone service agreement.',
    archivedAt: relativeDate(-30),
  },
  {
    vendorName: 'PixelCraft Agency',
    categoryName: 'Marketing',
    description: 'Seasonal campaign retainer',
    amount: '1500.00',
    currency: 'USD',
    frequency: 'MONTHLY' as const,
    nextDueDate: relativeDate(-60),
    notes: 'Retired campaign support arrangement.',
    archivedAt: relativeDate(-21),
  },
];
