import { relativeDate } from './dates';

export const vendors = [
  {
    name: 'Atlas Office Supplies',
    email: 'contact@atlasoffice.example.com',
    phone: '+12025550101',
    website: 'https://atlasoffice.example.com',
    notes: 'Office supplies and stationery vendor.',
  },
  {
    name: 'Nova Tech Solutions',
    email: 'hello@novatech.example.uk',
    phone: '+442071838002',
    website: 'https://novatech.example.uk',
    notes: 'IT equipment and software services.',
  },
  {
    name: 'Green Market Foods',
    email: 'orders@greenmarket.example.com',
    phone: '+12025550103',
    website: 'https://greenmarket.example.com',
    notes: 'Food and grocery supplier.',
  },
  {
    name: 'Bright Print Studio',
    email: 'sales@brightprint.example.uk',
    phone: '+442071838004',
    website: 'https://brightprint.example.uk',
    notes: 'Printing and branding services.',
  },
  {
    name: 'Urban Delivery Co',
    email: 'support@urbandelivery.example.com',
    phone: '+12025550105',
    website: 'https://urbandelivery.example.com',
    notes: 'Courier and local delivery service.',
  },
  {
    name: 'CloudPoint Hosting',
    email: 'billing@cloudpoint.example.de',
    phone: '+49301234506',
    website: 'https://cloudpoint.example.de',
    notes: 'Hosting and cloud infrastructure provider.',
  },
  {
    name: 'PixelCraft Agency',
    email: 'team@pixelcraft.example.fr',
    phone: '+33142340007',
    website: 'https://pixelcraft.example.fr',
    notes: 'Design, marketing, and creative services.',
  },
  {
    name: 'SafeBuild Maintenance',
    email: 'info@safebuild.example.com',
    phone: '+12025550108',
    website: 'https://safebuild.example.com',
    notes: 'Repairs, maintenance, and facility services.',
  },
  {
    name: 'Metro Fuel Services',
    email: 'accounts@metrofuel.example.com',
    phone: '+12025550109',
    website: 'https://metrofuel.example.com',
    notes: 'Fuel and vehicle-related expenses.',
  },
  {
    name: 'PureClean Supplies',
    email: 'contact@pureclean.example.uk',
    phone: '+442071838010',
    website: 'https://pureclean.example.uk',
    notes: 'Cleaning products and hygiene supplies.',
  },
  {
    name: 'Northstar Coworking',
    email: 'billing@northstar.example.com',
    phone: '+12025550111',
    website: 'https://northstar.example.com',
    notes: 'Flexible workspace and meeting room provider.',
  },
  {
    name: 'Harbor Business Travel',
    email: 'bookings@harbortravel.example.com',
    phone: '+12025550112',
    website: 'https://harbortravel.example.com',
    notes: 'Business travel and accommodation agency.',
  },
  {
    name: 'SecureNet Systems',
    email: 'accounts@securenet.example.de',
    phone: '+49301234513',
    website: 'https://securenet.example.de',
    notes: 'Network security and managed IT services.',
  },
  {
    name: 'Cedar Office Furniture',
    email: 'sales@cedaroffice.example.com',
    phone: '+12025550114',
    website: 'https://cedaroffice.example.com',
    notes: 'Desks, chairs, and office storage supplier.',
  },
  {
    name: 'Harbor Conference Center',
    email: 'events@harborconference.example.uk',
    phone: '+442071838015',
    website: 'https://harborconference.example.uk',
    notes: 'Conference rooms and corporate event services.',
  },
  {
    name: 'Legacy Telecom Services',
    email: 'billing@legacytelecom.example.fr',
    phone: '+33142340016',
    website: 'https://legacytelecom.example.fr',
    notes: 'Former office telephone service provider.',
    archivedAt: relativeDate(-37),
  },
  {
    name: 'Old Town Event Hire',
    email: 'hello@oldtownevents.example.uk',
    phone: '+442071838017',
    website: 'https://oldtownevents.example.uk',
    notes: 'Former event equipment and venue supplier.',
    archivedAt: relativeDate(-21),
  },
];
